// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmgzrtibogoqdgcefzey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZ3pydGlib2dvcWRnY2VmemV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5OTk3NzcsImV4cCI6MjA1MzU3NTc3N30.dzAXIkiV4dgmnXgqiKoPePp8HIbTEy20fPHjS3_WFuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);